export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_TOTAL_PRODUCT_COUNT: "SET_TOTAL_PRODUCT_COUNT",
    SET_LOADED: "SET_LOADED",
}